<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;

class MobileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create('App\Mobiles');
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('mobiles')->truncate();
        DB::table('mobiles')->insert([
            [
                'id' => 1,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 2,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 3,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 4,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 5,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 6,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 7,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 8,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 9,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 10,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 11,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 12,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 13,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 14,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 15,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 16,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 17,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 18,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 19,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'id' => 20,
                'categoryID' => 1,
                'brandID' => $faker->numberBetween(1, 8),
                'name' => $faker->streetName,
                'quantity' => $faker->numberBetween(1, 9) * 100,
                'status' => $faker->numberBetween(-1, 3),
                'saleOff' => $faker->numberBetween(1, 7) * 0.1,
                'price' => $faker->numberBetween(3, 20) * 1000000,
                'thumbnail' => 'https://res.cloudinary.com/quynv300192/image/upload/v1637650431/etvywgpmn5mkseimiiqe.jpg',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'detail' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
                'color' => 'white',
                'ram' => $faker->numberBetween(1, 4) * 4,
                'memory' => $faker->numberBetween(1, 4) * 512,
                'pin' => $faker->numberBetween(1, 3) * 1000, //mAh
                'camera' => $faker->numberBetween(8, 20),
                'screenSize' => $faker->numberBetween(6, 8),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]
        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}
