<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create('App\Orders');
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('orders')->truncate();
        DB::table('orders')->insert([
            [
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-3),
                'updated_at'=>Carbon::now()->addMonth(-3)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-84),
                'updated_at'=>Carbon::now()->addDay(-84)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-84),
                'updated_at'=>Carbon::now()->addDay(-84)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-81),
                'updated_at'=>Carbon::now()->addDay(-81)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-81),
                'updated_at'=>Carbon::now()->addDay(-81)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-78),
                'updated_at'=>Carbon::now()->addDay(-78)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-78),
                'updated_at'=>Carbon::now()->addDay(-78)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-75),
                'updated_at'=>Carbon::now()->addDay(-75)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-75),
                'updated_at'=>Carbon::now()->addDay(-75)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-72),
                'updated_at'=>Carbon::now()->addDay(-72)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-72),
                'updated_at'=>Carbon::now()->addDay(-72)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-69),
                'updated_at'=>Carbon::now()->addDay(-69)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-69),
                'updated_at'=>Carbon::now()->addDay(-69)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-66),
                'updated_at'=>Carbon::now()->addDay(-66)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-66),
                'updated_at'=>Carbon::now()->addDay(-66)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-63),
                'updated_at'=>Carbon::now()->addDay(-63)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-63),
                'updated_at'=>Carbon::now()->addDay(-63)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-60),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-60),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-57),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-57),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-54),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-54),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-51),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-51),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-48),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-48),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-45),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-45),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-42),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-42),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-39),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-39),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-36),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-36),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-33),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-33),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-30),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-30),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-27),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-27),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-24),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-24),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-21),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-21),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-18),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-18),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-15),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-15),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-12),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-12),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-9),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-9),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-6),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-6),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-3),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addDay(-3),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ]
        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}
