<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create('App\Orders');
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('orders')->truncate();
        DB::table('orders')->insert([
            [
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-1),
                'updated_at'=>Carbon::now()->addMonth(-1)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-2),
                'updated_at'=>Carbon::now()->addMonth(-2)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-3),
                'updated_at'=>Carbon::now()->addMonth(-3)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-4),
                'updated_at'=>Carbon::now()->addMonth(-4)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-5),
                'updated_at'=>Carbon::now()->addDay(-81)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-6),
                'updated_at'=>Carbon::now()->addDay(-78)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-8),
                'updated_at'=>Carbon::now()->addDay(-78)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-9),
                'updated_at'=>Carbon::now()->addDay(-75)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-10),
                'updated_at'=>Carbon::now()->addDay(-75)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-11),
                'updated_at'=>Carbon::now()->addDay(-72)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-3),
                'updated_at'=>Carbon::now()->addDay(-72)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-4),
                'updated_at'=>Carbon::now()->addDay(-69)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-5),
                'updated_at'=>Carbon::now()->addDay(-69)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-6),
                'updated_at'=>Carbon::now()->addDay(-66)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-7),
                'updated_at'=>Carbon::now()->addDay(-66)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-8),
                'updated_at'=>Carbon::now()->addDay(-63)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-9),
                'updated_at'=>Carbon::now()->addDay(-63)
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-3),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-3),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-4),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-5),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-6),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-7),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-8),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-10),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-11),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-12),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-1),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-3),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-2),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-4),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-5),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-6),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-7),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-8),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-9),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-10),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-7),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-3),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-3),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-2),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-3),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-11),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-11),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-10),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-10),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-10),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-11),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-9),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-9),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-9),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-8),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-8),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-8),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-8),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-7),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-7),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-6),
                'updated_at'=>Carbon::now()
            ],[
                'userId'=> 1,
                'status'=> $faker->numberBetween(0,3),
                'name'=>  $faker ->name,
                'comment'=> $faker ->sentence,
                'address'=>  $faker->address,
                'phone'=>  $faker->phoneNumber(),
                'email'=>  $faker->email,
                'totalPrice'=>  $faker->numberBetween(1,10)*10000000,
                'checkOut'=>  true,
                'created_at'=>Carbon::now()->addMonth(-6),
                'updated_at'=>Carbon::now()
            ]
        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}
